# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aerial Robotics Kharagpur
email: aerialroboticskharagpur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are an enthusiastic group of students working towards building autonomous aerial vehicles, based at Indian Institute of Technology Kharagpur.
  We are advised by Prof. Jayanta Mukhopadhyay of the Department of Computer Science and Engineering and Prof. D.K Pratihar of the Department of Mechanical Engineering and are funded by the Sponsored Research and Industrial Consultancy facility of IIT Kharagpur as part of Centre for Excellence in Robotics, IIT Kharagpur.
  The principal investigator for this project is Prof. Somesh Kumar, President, Technology Students' Gymkhana
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  quadrotor-iitkgp

# Build settings
markdown: kramdown
theme: minima
exclude: [vendor]
